### ISSUE TITLE
Introductory reading material

### ISSUE THREAD

**Issue by tdido** [tdido/board_alegosto01#1]
- [x] [Multiple Myeloma Guide](https://www.cancer.net/cancer-types/multiple-myeloma/introduction)
- [x] [A decade of structural variants: description, history and methods to detect structural variation](https://academic.oup.com/bfg/article/14/5/305/184088)
- [x] [Structural variant calling: the long and the short of it](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1828-7)
- [x] [Revealing the Impact of Structural Variants in Multiple Myeloma](https://aacrjournals.org/bloodcancerdiscov/article/1/3/258/65/Revealing-the-Impact-of-Structural-Variants-in)

**Comment by alegosto01** [comment]
last paper was really tough, i didn't understand it fully

**Comment by tdido** [comment]
Yes, that would be the toughest one. I wouldn't worry too much, you'll pick up those concepts along the way.

**Comment by alegosto01** [comment]
perfect, now i'm doing snakemake tutorial
